import {
  LayoutDashboard,
  MessageSquare,
  AlertTriangle,
  Compass,
  CheckSquare,
  TrendingUp,
  BookOpen,
  FileText,
  Zap,
  Settings,
  ShieldAlert,
  HelpCircle,
  Sliders,
  CreditCard,
  Sparkles,
  Bot,
  Wrench,
  GitBranch,
  Workflow,
  Layers,
  Users,
  Puzzle,
  Database,
  Network,
  Code,
  Share2,
  Briefcase,
  LucideProps,
} from "lucide-react";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  LayoutDashboard,
  MessageSquare,
  AlertTriangle,
  Compass,
  CheckSquare,
  TrendingUp,
  BookOpen,
  FileText,
  Zap,
  Settings,
  ShieldAlert,
  HelpCircle,
  Sliders,
  CreditCard,
  Sparkles,
  Bot,
  Wrench,
  GitBranch,
  Workflow,
  Layers,
  Users,
  Puzzle,
  Database,
  Network,
  Code,
  Share2,
  Briefcase,
};

export function DynamicIcon({ name, ...props }: { name: string } & LucideProps) {
  const IconComponent = ICON_MAP[name] || HelpCircle;
  return <IconComponent {...props} />;
}
