import { BusinessCategory, CountryHierarchy, DataPalSearchCampaign, TargetProfilePreset } from "./types";

export const TARGET_PROFILE_PRESETS: TargetProfilePreset[] = [
  {
    id: "all",
    label: "All Verified Businesses",
    desc: "Extract all matching operational local & enterprise listings without constraint",
    badge: "General",
  },
  {
    id: "website",
    label: "Missing Website",
    desc: "Businesses with offline operations or social pages but no official dedicated domain",
    badge: "High Conversion",
    suggestedCategories: ["Restaurants", "Gyms & Fitness Centers", "Dental Clinics", "Auto Repair & Garages"],
  },
  {
    id: "logo",
    label: "Missing Logo / Branding",
    desc: "Unbranded listings lacking custom creative identity, logo marks or visual branding",
    badge: "Creative Pitch",
    suggestedCategories: ["Wholesalers & Distributors", "Builders & Contractors", "Retail Stores"],
  },
  {
    id: "gbp",
    label: "Missing Google Business Profile",
    desc: "Unclaimed or incomplete Google Maps pins ready for Local SEO optimization",
    badge: "Local SEO",
    suggestedCategories: ["Medical Clinics", "Law Firms & Attorneys", "Salons & Hairdressers"],
  },
  {
    id: "social",
    label: "Missing Social Media Presence",
    desc: "Businesses with zero active Instagram, Facebook, or LinkedIn integration",
    badge: "Agency Lead",
    suggestedCategories: ["Cafes & Coffee Shops", "Aesthetic Clinics", "Jewelry & Watches"],
  },
  {
    id: "online_ordering",
    label: "Missing Online Ordering & Booking",
    desc: "Service businesses lacking automated digital reservation or delivery portals",
    badge: "SaaS Pitch",
    suggestedCategories: ["Restaurants", "Spas & Wellness Centers", "Diagnostic Centers"],
  },
  {
    id: "low_reviews",
    label: "Low Review Volume / Reputation Gap",
    desc: "High traffic businesses with fewer than 15 reviews or sub-4.0 star ratings",
    badge: "Reputation Mgmt",
    suggestedCategories: ["Hotels", "Supermarkets & Grocery", "Property Management"],
  },
];

export const COUNTRY_HIERARCHIES: CountryHierarchy[] = [
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    phonePrefix: "+91",
    postalCodeLabel: "PIN Code",
    states: [
      {
        name: "Maharashtra",
        cities: ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Navi Mumbai", "Aurangabad", "Solapur", "Kolhapur"],
      },
      {
        name: "Delhi NCR",
        cities: ["New Delhi", "Gurgaon (Gurugram)", "Noida", "Greater Noida", "Faridabad", "Ghaziabad", "South Delhi", "Connaught Place"],
      },
      {
        name: "Karnataka",
        cities: ["Bangalore (Bengaluru)", "Mysore", "Hubli-Dharwad", "Mangalore", "Belgaum", "Gulbarga", "Whitefield", "Indiranagar", "Koramangala"],
      },
      {
        name: "Tamil Nadu",
        cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tiruppur", "Vellore", "Erode"],
      },
      {
        name: "Telangana",
        cities: ["Hyderabad", "Secunderabad", "HITEC City", "Gachibowli", "Warangal", "Nizamabad", "Karimnagar"],
      },
      {
        name: "Gujarat",
        cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar"],
      },
      {
        name: "Uttar Pradesh",
        cities: ["Lucknow", "Kanpur", "Varanasi", "Agra", "Prayagraj (Allahabad)", "Meerut", "Bareilly", "Aligarh", "Gorakhpur"],
      },
      {
        name: "West Bengal",
        cities: ["Kolkata", "Howrah", "Salt Lake", "New Town", "Durgapur", "Asansol", "Siliguri"],
      },
      {
        name: "Rajasthan",
        cities: ["Jaipur", "Jodhpur", "Kota", "Udaipur", "Ajmer", "Bikaner", "Bhilwara"],
      },
      {
        name: "Punjab & Chandigarh",
        cities: ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Mohali", "Bathinda"],
      },
      {
        name: "Kerala",
        cities: ["Kochi (Cochin)", "Thiruvananthapuram", "Kozhikode (Calicut)", "Thrissur", "Kollam"],
      },
      {
        name: "Madhya Pradesh",
        cities: ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"],
      },
      {
        name: "Goa",
        cities: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Calangute"],
      },
    ],
  },
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    phonePrefix: "+1",
    postalCodeLabel: "ZIP Code",
    states: [
      {
        name: "California",
        cities: ["Los Angeles", "San Francisco", "San Jose", "San Diego", "Beverly Hills", "Irvine", "Sacramento", "Oakland"],
      },
      {
        name: "New York",
        cities: ["New York City", "Manhattan", "Brooklyn", "Queens", "Buffalo", "Rochester", "Albany"],
      },
      {
        name: "Texas",
        cities: ["Austin", "Houston", "Dallas", "San Antonio", "Fort Worth", "Plano"],
      },
      {
        name: "Florida",
        cities: ["Miami", "Orlando", "Tampa", "Fort Lauderdale", "Jacksonville"],
      },
      {
        name: "Washington",
        cities: ["Seattle", "Bellevue", "Redmond", "Tacoma", "Spokane"],
      },
    ],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    phonePrefix: "+971",
    postalCodeLabel: "Makani / PO Box",
    states: [
      {
        name: "Dubai",
        cities: ["Downtown Dubai", "Dubai Marina", "Business Bay", "Deira", "JLT", "Al Barsha", "Palm Jumeirah"],
      },
      {
        name: "Abu Dhabi",
        cities: ["Abu Dhabi City", "Al Reem Island", "Yas Island", "Al Ain"],
      },
      {
        name: "Sharjah & Northern Emirates",
        cities: ["Sharjah City", "Ajman", "Ras Al Khaimah"],
      },
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    phonePrefix: "+44",
    postalCodeLabel: "Postcode",
    states: [
      {
        name: "Greater London",
        cities: ["Central London", "City of London", "Westminster", "Canary Wharf", "Shoreditch", "Camden"],
      },
      {
        name: "North West & Midlands",
        cities: ["Manchester", "Birmingham", "Liverpool", "Leeds", "Sheffield"],
      },
    ],
  },
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    phonePrefix: "+65",
    postalCodeLabel: "Postal Code",
    states: [
      {
        name: "Singapore",
        cities: ["Marina Bay", "Orchard", "Central Business District (CBD)", "Jurong", "Tampines"],
      },
    ],
  },
];

export const BUSINESS_CATEGORIES: BusinessCategory[] = [
  {
    id: "healthcare",
    name: "Healthcare & Medical",
    icon: "Stethoscope",
    subcategories: [
      "Hospitals",
      "Medical Clinics",
      "Dental Clinics",
      "Pharmacies",
      "Diagnostic Centers",
      "Physical Therapy",
      "Eye Clinics & Optometrists",
      "Ayurvedic & Homeopathy Centers",
    ],
  },
  {
    id: "food_hospitality",
    name: "Food, Dining & Hospitality",
    icon: "Utensils",
    subcategories: [
      "Restaurants & Fine Dining",
      "Cafes & Coffee Shops",
      "Hotels & Boutique Resorts",
      "Bakeries & Patisseries",
      "Bars & Lounges",
      "Catering Services",
      "Cloud Kitchens & Food Hubs",
    ],
  },
  {
    id: "real_estate",
    name: "Real Estate & Construction",
    icon: "Building",
    subcategories: [
      "Real Estate Developers",
      "Builders & Contractors",
      "Architects",
      "Interior Designers",
      "Real Estate Brokerages",
      "Property Management Firms",
      "Commercial Real Estate",
    ],
  },
  {
    id: "technology",
    name: "Technology & IT",
    icon: "Laptop",
    subcategories: [
      "IT & Software Companies",
      "SaaS Startups",
      "Tech Consulting",
      "Web Design & Development",
      "Cybersecurity Firms",
      "Cloud Solutions",
      "AI & Automation Services",
      "Digital Marketing Agencies",
    ],
  },
  {
    id: "retail_ecommerce",
    name: "Retail & E-Commerce",
    icon: "ShoppingBag",
    subcategories: [
      "Retail Stores & Boutiques",
      "E-commerce Brands",
      "Supermarkets & Grocery",
      "Fashion & Apparel",
      "Electronics & Appliances",
      "Jewelry & Watches",
      "Wholesalers & Distributors",
    ],
  },
  {
    id: "professional_services",
    name: "Professional & Legal Services",
    icon: "Briefcase",
    subcategories: [
      "Law Firms & Advocates",
      "Chartered Accountants (CA/CS)",
      "Management Consulting",
      "Public Relations (PR) Agencies",
      "Financial & Investment Advisors",
      "Tax & GST Consultants",
    ],
  },
  {
    id: "fitness_beauty",
    name: "Fitness, Beauty & Wellness",
    icon: "Sparkles",
    subcategories: [
      "Gyms & Fitness Centers",
      "Yoga & Pilates Studios",
      "Luxury Salons & Hairdressers",
      "Spas & Wellness Resorts",
      "Aesthetic & Dermatology Clinics",
    ],
  },
  {
    id: "education",
    name: "Education & Academics",
    icon: "GraduationCap",
    subcategories: [
      "Universities & Colleges",
      "Private International Schools",
      "IIT-JEE & NEET Coaching Centers",
      "EdTech Academies",
      "Vocational & Skill Institutes",
    ],
  },
  {
    id: "logistics_automotive",
    name: "Logistics, Transport & Auto",
    icon: "Truck",
    subcategories: [
      "Manufacturing Units",
      "Logistics & Freight Forwarders",
      "Transport Fleet Companies",
      "Automobile Dealerships",
      "Auto Repair & Service Centers",
    ],
  },
];

export const DIRECTORY_SOURCES = [
  { id: "gmaps", name: "Google Maps & Places", icon: "MapPin", color: "#4285F4" },
  { id: "justdial", name: "JustDial India", icon: "PhoneCall", color: "#FF6600" },
  { id: "indiamart", name: "IndiaMART B2B", icon: "Building2", color: "#00AEEF" },
  { id: "tradeindia", name: "TradeIndia", icon: "Briefcase", color: "#2E7D32" },
  { id: "linkedin", name: "LinkedIn Company Search", icon: "Users", color: "#0A66C2" },
  { id: "yellowpages", name: "YellowPages Directory", icon: "BookOpen", color: "#F59E0B" },
];

export const SAMPLE_HISTORIC_CAMPAIGNS: DataPalSearchCampaign[] = [
  {
    id: "camp_mumbai_dental_2026",
    title: "Mumbai Dental Clinics Missing Websites",
    requirement: "Missing Website",
    location: "Mumbai, Maharashtra, India",
    countryCode: "IN",
    businessTypes: ["Dental Clinics", "Aesthetic & Dermatology Clinics"],
    totalExtracted: 28,
    phoneCount: 28,
    emailCount: 22,
    websiteCount: 0,
    opportunityCount: 28,
    createdAt: "2026-09-24T14:30:00Z",
    status: "completed",
    results: [
      {
        id: "lead_mb_1",
        name: "Dr. Kothari's Advanced Dental Care",
        category: "Dental Clinics",
        website: null,
        phone: "+91 98201 44321",
        email: "dr.kothari.dentist@gmail.com",
        address: "Shop 4, Silver Arch, Linking Road, Bandra West",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postalCode: "400050",
        rating: 4.8,
        reviewsCount: 164,
        existingPresence: "Google Maps, JustDial",
        source: "Google Maps & Places",
        notes: "🔥 Urgent Opportunity: 160+ 5-star reviews on Maps but NO website. Needs patient booking portal & smile makeover gallery.",
        verified: true,
        opportunityLevel: "Critical",
        tags: ["No Website", "High Rating", "Bandra VIP Area"],
        extractedAt: "2026-09-24T14:30:10Z",
      },
      {
        id: "lead_mb_2",
        name: "SmileCraft Orthodontic Center",
        category: "Dental Clinics",
        website: null,
        phone: "+91 98192 88710",
        email: "smilecraft.ortho.mumbai@gmail.com",
        address: "2nd Floor, Crystal Plaza, New Link Road, Andheri West",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postalCode: "400053",
        rating: 4.7,
        reviewsCount: 98,
        existingPresence: "Instagram, JustDial",
        source: "JustDial India",
        notes: "Only operates Instagram page with linktree to WhatsApp. High willingness to pay for dedicated brand website & SEO.",
        verified: true,
        opportunityLevel: "Critical",
        tags: ["No Website", "Instagram Only"],
        extractedAt: "2026-09-24T14:30:12Z",
      },
      {
        id: "lead_mb_3",
        name: "Apex Aesthetic & Dental Studio",
        category: "Aesthetic & Dermatology Clinics",
        website: null,
        phone: "+91 99304 11209",
        email: "contact.apexaesthetics@gmail.com",
        address: "Suite 102, Nariman Bhavan, Nariman Point",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postalCode: "400021",
        rating: 4.9,
        reviewsCount: 210,
        existingPresence: "Google Maps, Practo",
        source: "Google Maps & Places",
        notes: "South Mumbai premium aesthetic practice. Relies on Practo commission fees. Pitch custom consultation scheduling SaaS.",
        verified: true,
        opportunityLevel: "High",
        tags: ["South Mumbai", "No Website", "Practo Dependent"],
        extractedAt: "2026-09-24T14:30:14Z",
      },
      {
        id: "lead_mb_4",
        name: "GlowAura Skin & Hair Clinic",
        category: "Aesthetic & Dermatology Clinics",
        website: null,
        phone: "+91 97690 33418",
        email: null,
        address: "Opp. R-City Mall, LBS Marg, Ghatkopar West",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postalCode: "400086",
        rating: 4.6,
        reviewsCount: 75,
        existingPresence: "JustDial, Google Maps",
        source: "JustDial India",
        notes: "WhatsApp number verified. Needs professional email setup, logo redesign, and lead capture landing page.",
        verified: true,
        opportunityLevel: "High",
        tags: ["WhatsApp Verified", "No Website"],
        extractedAt: "2026-09-24T14:30:15Z",
      },
      {
        id: "lead_mb_5",
        name: "Metro Dental & Implant Clinic",
        category: "Dental Clinics",
        website: null,
        phone: "+91 98213 55678",
        email: "metrodentalclinic@rediffmail.com",
        address: "Near Dadar TT Circle, Dr. Babasaheb Ambedkar Road, Dadar East",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        postalCode: "400014",
        rating: 4.5,
        reviewsCount: 112,
        existingPresence: "Google Maps, YellowPages",
        source: "Google Maps & Places",
        notes: "Established 15-year clinic using obsolete Rediffmail address. Massive upgrade candidate for Google Workspace + Modern Web.",
        verified: true,
        opportunityLevel: "High",
        tags: ["Established 15+ Yrs", "Legacy Mail"],
        extractedAt: "2026-09-24T14:30:17Z",
      },
    ],
  },
  {
    id: "camp_bangalore_saas_2026",
    title: "Bangalore Tech Startups & Software Providers",
    requirement: "All Verified Businesses",
    location: "Bangalore (Bengaluru), Karnataka, India",
    countryCode: "IN",
    businessTypes: ["IT & Software Companies", "AI & Automation Services"],
    totalExtracted: 35,
    phoneCount: 35,
    emailCount: 35,
    websiteCount: 35,
    opportunityCount: 24,
    createdAt: "2026-09-23T11:15:00Z",
    status: "completed",
    results: [
      {
        id: "lead_blr_1",
        name: "CognitiveFlow AI Systems",
        category: "AI & Automation Services",
        website: "https://cognitiveflow.ai",
        phone: "+91 80 4123 9900",
        email: "partnerships@cognitiveflow.ai",
        address: "4th Floor, Salarpuria Hall, 100 Feet Road, Indiranagar",
        city: "Bangalore (Bengaluru)",
        state: "Karnataka",
        country: "India",
        postalCode: "560038",
        rating: 4.9,
        reviewsCount: 42,
        existingPresence: "LinkedIn, GitHub, Crunchbase",
        source: "LinkedIn Company Search",
        notes: "High growth 28-person team. Seeking enterprise channel partnerships and distribution playbooks in GCC & US.",
        verified: true,
        opportunityLevel: "High",
        tags: ["Series A Candidate", "AI Tech"],
        extractedAt: "2026-09-23T11:15:05Z",
      },
      {
        id: "lead_blr_2",
        name: "ScaleMatrix Cloud Technologies",
        category: "IT & Software Companies",
        website: "https://scalematrix.in",
        phone: "+91 80 6789 2210",
        email: "growth@scalematrix.in",
        address: "EcoWorld Technology Campus, Outer Ring Road, Bellandur",
        city: "Bangalore (Bengaluru)",
        state: "Karnataka",
        country: "India",
        postalCode: "560103",
        rating: 4.7,
        reviewsCount: 56,
        existingPresence: "Google Maps, LinkedIn",
        source: "Google Maps & Places",
        notes: "Cloud DevOps engineering consultancy. Seeking lead gen to reach D2C & FinTech founders across Mumbai & Delhi.",
        verified: true,
        opportunityLevel: "Medium",
        tags: ["B2B Tech", "Cloud Infra"],
        extractedAt: "2026-09-23T11:15:08Z",
      },
    ],
  },
  {
    id: "camp_delhi_interiors_2026",
    title: "Delhi NCR Architects & Luxury Interior Designers",
    requirement: "Missing Online Ordering & Booking",
    location: "Delhi NCR, India",
    countryCode: "IN",
    businessTypes: ["Architects", "Interior Designers"],
    totalExtracted: 22,
    phoneCount: 22,
    emailCount: 19,
    websiteCount: 18,
    opportunityCount: 22,
    createdAt: "2026-09-22T09:00:00Z",
    status: "completed",
    results: [
      {
        id: "lead_del_1",
        name: "Aethelgard Architecture & Interiors",
        category: "Interior Designers",
        website: "https://aethelgarddesign.in",
        phone: "+91 98110 99882",
        email: "studio@aethelgarddesign.in",
        address: "Design District, MG Road, Sultanpur",
        city: "New Delhi",
        state: "Delhi NCR",
        country: "India",
        postalCode: "110030",
        rating: 4.9,
        reviewsCount: 68,
        existingPresence: "Instagram, Architectural Digest India",
        source: "Google Maps & Places",
        notes: "High-ticket residential projects (₹50L - ₹3Cr). Website is static portfolio; has no interactive 3D estimate calculator or CRM intake.",
        verified: true,
        opportunityLevel: "Critical",
        tags: ["High Net Worth", "Needs CRM Intake"],
        extractedAt: "2026-09-22T09:00:10Z",
      },
    ],
  },
];
