export interface CatalogTool {
  id: string;
  name: string;
  category: "finance" | "sales" | "marketing" | "operations" | "strategy";
  description: string;
  requiredPlan: "free" | "starter" | "growth" | "enterprise";
  badge: string;
  hasInteractiveCalculator: boolean;
  enabled: boolean;
}

export interface SubscriptionPlan {
  id: string;
  name: string;
  tagline: string;
  price: string;
  period: string;
  color: string;
  badge: string;
  isPopular: boolean;
  features: string[];
  ctaLabel: string;
  enabled: boolean;
}

export const DEFAULT_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: "free",
    name: "BizzPal Free / Demo",
    tagline: "Try BizzPal free to see how it works.",
    price: "₹0",
    period: "/forever",
    color: "border-emerald-400/30 text-emerald-400",
    badge: "Free Trial",
    isPopular: false,
    features: [
      "Business Dashboard",
      "CEO AI Assistant (Astra)",
      "Company Health Score",
      "Profit & ROI Calculators",
      "Save up to 5 Documents & SOPs",
      "Daily Business Briefings",
      "Task Manager",
      "Free AI questions",
    ],
    ctaLabel: "Start Free & Open Dashboard",
    enabled: true,
  },
  {
    id: "starter",
    name: "Starter Business OS",
    tagline: "For solo founders and early teams (1-5 people).",
    price: "₹3,999",
    period: "/month",
    color: "border-cyan-400/30 text-cyan-400",
    badge: "Most Popular",
    isPopular: true,
    features: [
      "All Free tier features",
      "All 3 AI Executives (CEO, CFO, CMO)",
      "Automated Daily 8:00 AM WhatsApp Briefings",
      "Connect 3 Business Tools (Stripe, Slack, Zoho)",
      "Cash Runway & Burn Alarm System",
      "Unlimited AI Strategy Consultations",
      "3 Team Member Seats",
      "Email & WhatsApp Support",
    ],
    ctaLabel: "Activate Starter Plan",
    enabled: true,
  },
  {
    id: "growth",
    name: "Growth Scale",
    tagline: "For expanding businesses ready to scale (5-30 people).",
    price: "₹9,999",
    period: "/month",
    color: "border-violet-400/30 text-violet-400",
    badge: "Recommended",
    isPopular: false,
    features: [
      "All Starter tier features",
      "Scenario Planner & Simulator",
      "Executive Playbooks & Growth Vectors",
      "Connect Unlimited Tools & Bank Accounts",
      "Weekly AI Strategic Audits",
      "Custom KPI Dashboards & Role-based Access",
      "10 Team Member Seats",
      "Dedicated Account Manager",
    ],
    ctaLabel: "Activate Growth Scale",
    enabled: true,
  },
  {
    id: "enterprise",
    name: "Enterprise Custom",
    tagline: "For mid-market companies & conglomerates (30+ people).",
    price: "Custom",
    period: "/billed annually",
    color: "border-amber-400/30 text-amber-400",
    badge: "Enterprise",
    isPopular: false,
    features: [
      "All Growth Scale features",
      "Self-hosted / Dedicated Cloud Deployment",
      "Custom AI Executive Models trained on your data",
      "Custom ERP & Legacy Integrations",
      "Enterprise SLA (99.9% uptime)",
      "Unlimited Seats & Departments",
      "SOC 2 Type II & ISO 27001 Compliance",
      "24/7 Executive Hotline",
    ],
    ctaLabel: "Contact Enterprise Sales",
    enabled: true,
  },
];

export const DEFAULT_DASHBOARD_FEATURES = {
  enableAiCopilot: true,
  enableDailyCheckin: true,
  enableCommandPalette: true,
  enableWhatsApp: true,
  enableToolsCatalog: true,
};

export const DEFAULT_TOOLS_CATALOG: CatalogTool[] = [
  // Finance Tools
  {
    id: "profit",
    name: "Profit Calculator",
    category: "finance",
    description: "Calculate gross, operating, and net margins with loaded Indian payroll & overheads.",
    requiredPlan: "starter",
    badge: "Unit Economics",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "cashflow",
    name: "Cash Flow Forecast",
    category: "finance",
    description: "Multi-month forward cash projections incorporating collections, net burn, and tax outlays.",
    requiredPlan: "growth",
    badge: "Runway Guard",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "breakeven",
    name: "Break-Even Calculator",
    category: "finance",
    description: "Determine exact monthly transaction volume and revenue required to reach zero net burn.",
    requiredPlan: "starter",
    badge: "Solvency",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "pricing",
    name: "Pricing Simulator",
    category: "finance",
    description: "Model tiered packaging, discounting thresholds, and margin impacts on Indian buyers.",
    requiredPlan: "growth",
    badge: "Revenue Ops",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "roi",
    name: "ROI Calculator",
    category: "finance",
    description: "Evaluate software licenses, capital expenditure, and vendor investments payback periods.",
    requiredPlan: "starter",
    badge: "Capital Efficiency",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "budget",
    name: "Budget Planner",
    category: "finance",
    description: "Departmental allocation limits across engineering, marketing, sales, and administration.",
    requiredPlan: "growth",
    badge: "Allocation",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "emi",
    name: "Business Loan & Equipment EMI Calculator",
    category: "finance",
    description: "Calculate commercial loan EMIs, interest outlays, amortization schedules, and monthly debt-burn impact.",
    requiredPlan: "starter",
    badge: "Debt & Financing",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "gst",
    name: "GST & Tax Offset Calculator",
    category: "finance",
    description: "Calculate forward/reverse GST amounts, CGST+SGST vs IGST split, and net Input Tax Credit (ITC) balance.",
    requiredPlan: "starter",
    badge: "Tax Compliance",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "working_capital",
    name: "Working Capital & Cash Cycle (CCC) Calculator",
    category: "finance",
    description: "Measure Days Sales Outstanding (DSO), Inventory (DIO), and Payables (DPO) to unlock trapped cash.",
    requiredPlan: "growth",
    badge: "Liquidity Velocity",
    hasInteractiveCalculator: true,
    enabled: true,
  },

  // Sales Tools
  {
    id: "sales_forecast",
    name: "Sales Forecast",
    category: "sales",
    description: "Weighted pipeline forecasting by deal stage, historical velocity, and deal probabilities.",
    requiredPlan: "starter",
    badge: "Pipeline",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "lead_scoring",
    name: "Lead Scoring Matrix",
    category: "sales",
    description: "Algorithmic ICP fit and engagement scoring to prioritize high-value inbound prospects.",
    requiredPlan: "growth",
    badge: "Conversion",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "pipeline",
    name: "Pipeline Analyzer",
    category: "sales",
    description: "Detect deal slippage, stage bottlenecks, and sales cycle deceleration across reps.",
    requiredPlan: "starter",
    badge: "Velocity",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "deal_simulator",
    name: "Deal Simulator",
    category: "sales",
    description: "Simulate multi-year enterprise contracts, SLA guarantees, and payment milestones.",
    requiredPlan: "growth",
    badge: "Enterprise",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "ltv",
    name: "Customer Lifetime Value (LTV)",
    category: "sales",
    description: "Cohort retention modeling, expansion revenue, and gross margin-adjusted customer value.",
    requiredPlan: "starter",
    badge: "Retention",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "discount_margin",
    name: "Discount & Margin Sensitivity Calculator",
    category: "sales",
    description: "Analyze how contract discounting erodes gross profit and calculate the extra volume required to break even.",
    requiredPlan: "starter",
    badge: "Margin Defense",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "nrr",
    name: "Net Revenue Retention (NRR) & Churn Calculator",
    category: "sales",
    description: "Model gross vs net revenue retention, logo vs expansion churn, and forward ARR impact.",
    requiredPlan: "growth",
    badge: "Retention Ops",
    hasInteractiveCalculator: true,
    enabled: true,
  },

  // Marketing Tools
  {
    id: "campaign",
    name: "Campaign Analyzer",
    category: "marketing",
    description: "Performance diagnostics across Google, LinkedIn, Meta, and organic content pipelines.",
    requiredPlan: "starter",
    badge: "Attribution",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "cac",
    name: "CAC Calculator",
    category: "marketing",
    description: "Calculate fully loaded Customer Acquisition Cost including team salaries and tools.",
    requiredPlan: "starter",
    badge: "Acquisition",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "roas",
    name: "ROAS Calculator",
    category: "marketing",
    description: "Direct return on ad spend versus organic pipeline contribution and payback cycles.",
    requiredPlan: "starter",
    badge: "Ad Efficiency",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "marketing_forecast",
    name: "Marketing Forecast",
    category: "marketing",
    description: "Predict MQL and SQL generation curves based on current budget allocation scenarios.",
    requiredPlan: "growth",
    badge: "Demand Gen",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "competitor",
    name: "Competitor Analyzer",
    category: "marketing",
    description: "Evaluate competitor positioning, feature parity, pricing gaps, and keyword capture.",
    requiredPlan: "growth",
    badge: "Market Intel",
    hasInteractiveCalculator: false,
    enabled: true,
  },

  // Operations Tools
  {
    id: "capacity",
    name: "Capacity Planner",
    category: "operations",
    description: "Evaluate team bandwidth, billable utilization rates, and operational strain thresholds.",
    requiredPlan: "growth",
    badge: "Fulfillment",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "inventory",
    name: "Inventory Simulator",
    category: "operations",
    description: "Holding cost, re-order trigger levels, and working capital cash lockup simulations.",
    requiredPlan: "growth",
    badge: "Supply Chain",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "workforce",
    name: "Workforce Planner",
    category: "operations",
    description: "FTE capacity modeling against annual growth targets and onboarding ramp lags.",
    requiredPlan: "growth",
    badge: "Staffing",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "process",
    name: "Process Analyzer",
    category: "operations",
    description: "Map end-to-end client delivery workflows to pinpoint handoff friction and delays.",
    requiredPlan: "enterprise",
    badge: "SLA Guard",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "loaded_cost",
    name: "Employee Fully-Loaded Cost Calculator",
    category: "operations",
    description: "Calculate true cost per hire including PF, health benefits, equipment, SaaS, and minimum billable rate.",
    requiredPlan: "starter",
    badge: "Talent Economics",
    hasInteractiveCalculator: true,
    enabled: true,
  },

  // Strategy Tools
  {
    id: "swot",
    name: "SWOT Analyzer",
    category: "strategy",
    description: "Interactive Strengths, Weaknesses, Opportunities, and Threats strategic mapping matrix.",
    requiredPlan: "starter",
    badge: "Strategic Matrix",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "market_entry",
    name: "Market Entry Simulator",
    category: "strategy",
    description: "Simulate entry costs, localized competition, and payback for new domestic or global markets.",
    requiredPlan: "growth",
    badge: "Expansion",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "scenario_planner",
    name: "Scenario Planner",
    category: "strategy",
    description: "Macro stress-testing: inflation, demand contraction, and competitor price wars.",
    requiredPlan: "growth",
    badge: "Risk Defense",
    hasInteractiveCalculator: false,
    enabled: true,
  },
  {
    id: "hiring",
    name: "Hiring Simulator",
    category: "strategy",
    description: "Fully loaded Indian payroll simulation including provident fund, benefits, and revenue lag.",
    requiredPlan: "growth",
    badge: "Talent Ops",
    hasInteractiveCalculator: true,
    enabled: true,
  },
  {
    id: "expansion",
    name: "Expansion Simulator",
    category: "strategy",
    description: "Capital requirements and projected ROI for opening new branch offices or enterprise teams.",
    requiredPlan: "enterprise",
    badge: "Scale Vector",
    hasInteractiveCalculator: false,
    enabled: true,
  },
];
