import { NavItem } from "../schemas/nav";

export const defaultNavItems: NavItem[] = [
  // Core items & mobile tabs
  {
    id: "nav_dashboard",
    label: "Dashboard",
    href: "/",
    icon: "LayoutDashboard",
    order: 1,
    mobileTab: true,
    group: "core",
    enabled: true,
  },
  {
    id: "nav_chat",
    label: "AI Executive Chat",
    href: "/chat",
    icon: "MessageSquare",
    order: 2,
    mobileTab: true,
    group: "core",
    enabled: true,
  },
  {
    id: "nav_gaps",
    label: "Gap Register",
    href: "/gaps",
    icon: "AlertTriangle",
    order: 3,
    badge: "5",
    mobileTab: true,
    group: "intelligence",
    enabled: true,
  },
  {
    id: "nav_simulator",
    label: "Decision Simulator",
    href: "/simulator",
    icon: "Compass",
    order: 4,
    mobileTab: false,
    group: "intelligence",
    enabled: true,
  },
  {
    id: "nav_tasks",
    label: "Tasks & Execution",
    href: "/tasks",
    icon: "CheckSquare",
    order: 5,
    mobileTab: true,
    group: "management",
    enabled: true,
  },
  {
    id: "nav_analytics",
    label: "Adaptive Analytics",
    href: "/analytics",
    icon: "TrendingUp",
    order: 6,
    mobileTab: false,
    group: "intelligence",
    enabled: true,
  },
  {
    id: "nav_knowledge",
    label: "Knowledge Hub",
    href: "/knowledge",
    icon: "BookOpen",
    order: 7,
    mobileTab: false,
    group: "intelligence",
    enabled: true,
  },
  {
    id: "nav_reports",
    label: "Executive Briefings",
    href: "/reports",
    icon: "FileText",
    order: 8,
    mobileTab: false,
    group: "management",
    enabled: true,
  },
  {
    id: "nav_automations",
    label: "Automations",
    href: "/automations",
    icon: "Zap",
    order: 9,
    mobileTab: false,
    group: "management",
    enabled: true,
  },
  {
    id: "nav_settings",
    label: "Settings",
    href: "/settings/appearance",
    icon: "Settings",
    order: 10,
    mobileTab: false,
    group: "system",
    enabled: true,
  },
  {
    id: "nav_subscription",
    label: "Plans & Billing",
    href: "/subscription",
    icon: "CreditCard",
    order: 11,
    mobileTab: false,
    group: "system",
    enabled: true,
  },
  {
    id: "nav_help",
    label: "Help & FAQs",
    href: "/help",
    icon: "HelpCircle",
    order: 12,
    mobileTab: false,
    group: "system",
    enabled: true,
  },
  // Note: Superadmin Plane removed from normal business navigation per user instructions.
  // Superadmin is accessible strictly via /admin/login by authorized developers.
];
