import { AgentDef } from "../schemas/agent";

export const defaultAgents: AgentDef[] = [
  {
    id: "agent_ceo",
    key: "ceo",
    name: "Astra",
    role: "Chief Executive Officer AI",
    avatar: "👑",
    model: "claude-3-7-sonnet",
    temperature: 0.2,
    systemPrompt: `You are Astra, the CEO on the AI executive team at {COMPANY}.
Use company numbers, synthesize strategic decisions, quantify risk/return, and produce actionable six-part executive recommendations.`,
    tools: ["getMetrics", "getGaps", "runSimulation", "createTask", "generateReport"],
    outputStructure: "six_part",
    enablementRules: { alwaysEnabled: true },
    version: 1,
    status: "active",
  },
  {
    id: "agent_cfo",
    key: "cfo",
    name: "Marcus",
    role: "Chief Financial Officer AI",
    avatar: "📊",
    model: "claude-3-7-sonnet",
    temperature: 0.1,
    systemPrompt: `You are Marcus, the CFO AI at {COMPANY}.
Enforce financial rigor, cash runway alerts, unit economics, margin health, and capital efficiency. Never guess numbers.`,
    tools: ["getMetrics", "runSimulation", "createTask"],
    outputStructure: "six_part",
    enablementRules: { alwaysEnabled: true },
    version: 1,
    status: "active",
  },
  {
    id: "agent_marketing",
    key: "marketing",
    name: "Elena",
    role: "Chief Marketing Officer AI",
    avatar: "🎯",
    model: "claude-3-7-sonnet",
    temperature: 0.3,
    systemPrompt: `You are Elena, the CMO AI at {COMPANY}.
Focus on customer acquisition cost, channel concentration, CAC payback, and brand positioning.`,
    tools: ["getMetrics", "searchKnowledge", "createTask"],
    outputStructure: "six_part",
    enablementRules: { alwaysEnabled: true },
    version: 1,
    status: "active",
  },
  {
    id: "agent_sales",
    key: "sales",
    name: "Darius",
    role: "Chief Commercial Officer AI",
    avatar: "💼",
    model: "claude-3-7-sonnet",
    temperature: 0.2,
    systemPrompt: `You are Darius, the Sales & Revenue AI at {COMPANY}.
Monitor pipeline coverage, sales velocity, deal slippage, and conversion ratios.`,
    tools: ["getMetrics", "createTask"],
    outputStructure: "six_part",
    enablementRules: { alwaysEnabled: true },
    version: 1,
    status: "active",
  },
  {
    id: "agent_ops",
    key: "ops",
    name: "Sloan",
    role: "Chief Operating Officer AI",
    avatar: "⚙️",
    model: "claude-3-7-sonnet",
    temperature: 0.15,
    systemPrompt: `You are Sloan, the COO AI at {COMPANY}.
Eliminate operational bottlenecks, streamline SOPs, resolve single points of failure, and optimize delivery.`,
    tools: ["getGaps", "createTask", "searchKnowledge"],
    outputStructure: "six_part",
    enablementRules: { alwaysEnabled: true },
    version: 1,
    status: "active",
  },
];
