import { WidgetDef } from "../schemas/widget";

export const defaultWidgets: WidgetDef[] = [
  {
    id: "widget_health_score",
    title: "Business Health Score",
    component: "HealthScoreWidget",
    priority: 100,
    defaultSpan: 2,
    minContainerWidth: 320,
    requires: {},
    enabled: true,
  },
  {
    id: "widget_daily_briefing",
    title: "Executive Intelligence Briefing",
    component: "BriefingWidget",
    priority: 95,
    defaultSpan: 2,
    minContainerWidth: 320,
    requires: {},
    enabled: true,
  },
  {
    id: "widget_kpi_board",
    title: "Primary Performance Indicators",
    component: "KpiGridWidget",
    priority: 90,
    defaultSpan: 4,
    minContainerWidth: 260,
    requires: {},
    enabled: true,
  },
  {
    id: "widget_top_gaps",
    title: "Priority Gaps & Bottlenecks",
    component: "GapsPreviewWidget",
    priority: 85,
    defaultSpan: 2,
    minContainerWidth: 320,
    requires: {},
    enabled: true,
  },
  {
    id: "widget_priority_tasks",
    title: "Execution Queue",
    component: "TasksPreviewWidget",
    priority: 80,
    defaultSpan: 2,
    minContainerWidth: 320,
    requires: {},
    enabled: true,
  },
  {
    id: "widget_simulator_highlight",
    title: "Active Decision Simulation",
    component: "SimulatorHighlightWidget",
    priority: 75,
    defaultSpan: 4,
    minContainerWidth: 320,
    requires: {},
    enabled: true,
  },
];
