import { NavItem } from "../schemas/nav";

export const defaultNavItems: NavItem[] = [
  // 1. CORE
  {
    id: "nav_dashboard",
    label: "Dashboard",
    href: "/dashboard",
    icon: "LayoutDashboard",
    order: 1,
    mobileTab: true,
    group: "core",
    enabled: true,
  },
  {
    id: "nav_chat",
    label: "AI Workspace",
    href: "/chat",
    icon: "Sparkles",
    order: 2,
    mobileTab: true,
    group: "core",
    enabled: true,
  },
  {
    id: "nav_strategy",
    label: "Growth Strategy",
    href: "/strategy",
    icon: "Compass",
    order: 3,
    badge: "NEW",
    mobileTab: false,
    group: "core",
    enabled: true,
  },
  {
    id: "nav_playbooks",
    label: "Executive Playbooks",
    href: "/playbooks",
    icon: "Compass",
    order: 4,
    badge: "PRO",
    mobileTab: false,
    group: "core",
    requiredPlan: "growth",
    enabled: true,
  },

  // 2. EXECUTIVE INTELLIGENCE
  {
    id: "nav_gaps",
    label: "Gap Register",
    href: "/gaps",
    icon: "AlertTriangle",
    order: 5,
    badge: "5",
    mobileTab: true,
    group: "intelligence",
    enabled: true,
  },
  {
    id: "nav_simulator",
    label: "Decision Simulator",
    href: "/simulator",
    icon: "Compass",
    order: 6,
    mobileTab: false,
    group: "intelligence",
    requiredPlan: "growth",
    enabled: true,
  },
  {
    id: "nav_analytics",
    label: "Adaptive Analytics",
    href: "/analytics",
    icon: "TrendingUp",
    order: 7,
    mobileTab: false,
    group: "intelligence",
    requiredPlan: "growth",
    enabled: true,
  },
  {
    id: "nav_knowledge",
    label: "Knowledge Hub",
    href: "/knowledge",
    icon: "BookOpen",
    order: 8,
    mobileTab: false,
    group: "intelligence",
    enabled: true,
  },
  {
    id: "nav_tools",
    label: "Tools",
    href: "/tools",
    icon: "Wrench",
    order: 9,
    mobileTab: false,
    group: "intelligence",
    enabled: true,
  },

  // 3. OPERATIONS & EXECUTION
  {
    id: "nav_tasks",
    label: "Tasks & Execution",
    href: "/tasks",
    icon: "CheckSquare",
    order: 10,
    mobileTab: true,
    group: "management",
    enabled: true,
  },
  {
    id: "nav_reports",
    label: "Executive Briefings",
    href: "/reports",
    icon: "FileText",
    order: 11,
    mobileTab: false,
    group: "management",
    enabled: true,
  },
  {
    id: "nav_automations",
    label: "Automations",
    href: "/automations",
    icon: "Zap",
    order: 12,
    mobileTab: false,
    group: "management",
    requiredPlan: "starter",
    enabled: true,
  },
  {
    id: "nav_workflows",
    label: "Workflows",
    href: "/workflows",
    icon: "GitBranch",
    order: 13,
    mobileTab: false,
    group: "management",
    requiredPlan: "growth",
    enabled: true,
  },

  // 4. PLATFORM
  {
    id: "nav_integrations",
    label: "Integrations",
    href: "/integrations",
    icon: "Layers",
    order: 14,
    mobileTab: false,
    group: "system",
    enabled: true,
  },
  {
    id: "nav_team",
    label: "Team & Permissions",
    href: "/team",
    icon: "Users",
    order: 15,
    mobileTab: false,
    group: "system",
    requiredPlan: "starter",
    enabled: true,
  },
  {
    id: "nav_settings",
    label: "Settings",
    href: "/settings/profile",
    icon: "Settings",
    order: 16,
    mobileTab: false,
    group: "system",
    enabled: true,
  },
  {
    id: "nav_subscription",
    label: "Plans & Billing",
    href: "/subscription",
    icon: "CreditCard",
    order: 17,
    mobileTab: false,
    group: "system",
    enabled: true,
  },
];
